import type { PromptId } from '../prompts/types.ts';

export function buildFallbackJson(promptId: PromptId): Record<string, unknown> {
  if (promptId === 'command_router') {
    return {
      intent_classified: 'generate_prd',
      confidence: 'medium',
      action_taken: 'Routed request to PRD generation pipeline.',
      output_type: 'prd',
      content: {},
      citations: [{ type: 'metric', id: 'unknown', label: 'No source found', link: '' }],
      confidence_note: 'Generated by deterministic fallback provider.',
      next_suggested_action: 'Review generated PRD draft.',
      warnings: ['No source found'],
      clarification_options: [],
      methodology_applied: {
        primary: 'rice',
        supporting: ['jtbd', 'scrum'],
        selection_reason: 'Fallback default methodology selection.',
      },
      methodology_outputs: {
        rice: { score: 1 },
      },
    };
  }

  if (promptId === 'prd_generation') {
    return {
      problem_statement: { what: 'No source found', who: 'PM user', impact_if_unsolved: 'Execution slows' },
      success_metrics: [],
      user_stories: [],
      acceptance_criteria: [],
      edge_cases: [],
      assumptions: [],
      open_questions: [],
      dependencies: [],
      out_of_scope: [],
      conflicts_detected: [],
      missing_context: ['No source found'],
      prioritization_framework: 'rice',
      delivery_framework: 'scrum',
      metrics_framework: 'okr_alignment',
      discovery_framework: 'jtbd',
      methodology_applied: {
        primary: 'rice',
        supporting: ['jtbd', 'scrum', 'okr_alignment'],
        selection_reason: 'Fallback default methodology selection.',
      },
      methodology_outputs: {
        rice: { score: 1 },
        jtbd: { recommendation: 'No source found' },
      },
    };
  }

  if (promptId === 'ticket_factory') {
    return {
      sprint_assessment: { total_estimated_sp: 0, total_estimated_days: 0, sprint_fit: 'needs_splitting', recommendation: 'No source found' },
      prd_gaps_found: ['No source found'],
      tickets: [],
      high_risk_tickets: [],
      planning_framework: 'scrum',
      capacity_model_assumptions: ['No source found'],
      risk_register: [{ type: 'risk', detail: 'No source found' }],
      methodology_applied: {
        primary: 'sprint_planning',
        supporting: ['scrum', 'raid'],
        selection_reason: 'Fallback default methodology selection.',
      },
      methodology_outputs: {
        sprint_planning: { cadence: '2-week sprint' },
      },
    };
  }

  if (promptId === 'decision_detection') {
    return {
      analysis_metadata: {
        source_type: 'unknown',
        participants_identified: [],
        conversation_summary: 'No source found',
        total_decisions_found: 0,
        total_candidates_found: 0,
      },
      decisions: [],
      decision_candidates: [],
      action_items_detected: [],
    };
  }

  if (promptId === 'daily_digest') {
    return {
      summary: 'No risks detected.',
      risks: [],
      priorities: [],
      health_score: { score: 50, previous_score: 50, change: 0, change_driver: 'No source found' },
      assumption_alerts: [],
    };
  }

  if (promptId === 'opportunities_synthesize') {
    return {
      opportunities: [],
      synthesis_summary: 'No source found',
      evidence_gaps: ['No source found'],
      total_evidence_chunks: 0,
    };
  }

  if (promptId === 'methodology_reasoning') {
    return {
      reasoning: 'No source found',
      recommendation: 'No source found',
    };
  }

  if (promptId === 'prd_health') {
    return {
      health_score: 50,
      grade: 'C (60-74)',
      ready_for_engineering: false,
      blocking_issues: ['No source found'],
      breakdown: {},
      top_3_fixes: [],
      conflicts_with_product: [],
      okr_alignment: { aligned: false, which_okr: 'No source found', alignment_note: 'No source found' },
      methodology_completeness: 0.5,
      methodology_data_sufficiency: 0.4,
      methodology_contradictions: [],
      methodology_applied: {
        primary: 'okr_alignment',
        supporting: ['raid'],
        selection_reason: 'Fallback default methodology selection.',
      },
      methodology_outputs: {
        okr_alignment: { aligned: false },
      },
    };
  }

  return {
    audience: 'executive',
    subject_line: 'No source found',
    body: 'No source found',
    word_count: 3,
    key_metrics_included: [],
    asks_or_decisions_needed: [],
    tone_check: 'No source found',
    alternative_subject_lines: [],
  };
}
